version: "3.8"
services:

  nginx:
    image: nginx:latest
    container_name: nacos-cluster-nginx
    volumes:
      - ../build/conf/nginx-ip.conf:/etc/nginx/nginx.conf
    ports:
      - 8848:80
    networks:
      nacos_net:
        ipv4_address: 172.16.238.2

  nacos1:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-cluster-1
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs
    env_file:
      - ../env/nacos-ip.env
    restart: on-failure
    networks:
      nacos_net:
        ipv4_address: 172.16.238.10
    depends_on:
      mysql:
        condition: service_healthy

  nacos2:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-cluster-2
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    env_file:
      - ../env/nacos-ip.env
    restart: always
    networks:
      nacos_net:
        ipv4_address: 172.16.238.11
    depends_on:
      mysql:
        condition: service_healthy

  nacos3:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-cluster-3
    volumes:
      - ./cluster-logs/nacos2:/home/nacos/logs
    env_file:
      - ../env/nacos-ip.env
    restart: always
    networks:
      nacos_net:
        ipv4_address: 172.16.238.12
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: nacos/mysql:8
    container_name: nacos-cluster-mysql-8
    build:
      context: .
      dockerfile: ./image/mysql/8/Dockerfile
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      nacos_net:
        ipv4_address: 172.16.238.13
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  nacos_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
